---
- hosts: webservers
  become: true

  tasks:

    - name: Check number of processors
      command: nproc

    - name: Check RAM usage
      command: free -h

    - name: Check disk usage
      command: df -h

    - name: Check running processes
      command: ps -ef
